### PR TITLE
Update to 5.39 and merge libmagic

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by chrisburr** [comment]
@conda-forge/file @conda-forge/libmagic I propose merging `libmagic` with `file`, archiving `libmagic` and using a single multi-output recipe (i.e. this PR) to split the `file` binary from the `libmagic.so` library. The reason being that they're currently building the same package and they clobber each other when used together.

Also closes https://github.com/conda-forge/libmagic-feedstock/issues/3

**Review by mrakitin — APPROVED** [review]
Thanks @chrisburr, the plan sounds good to me. Feel free to merge after you receive the feedback from another feedstock's maintainers.

**Comment by mrakitin** [comment]
@chrisburr, do you want to become a maintainer? ;)

**Comment by chrisburr** [comment]
No good deed goes unpunished... 😆

I've also added @mariusvniekerk as they're the only member of the libmagic team. Is this okay Marius?

**Comment by mariusvniekerk** [comment]
That's fine by me

**Comment by chrisburr** [comment]
In which case over to you @mrakitin to merge this!

**Comment by mrakitin** [comment]
@conda-forge-admin, please rerender.

**Comment by mrakitin** [comment]
Thanks @chrisburr and @mariusvniekerk! Rerendering to get your names in the codeowners.

**Comment by chrisburr** [comment]
Thanks! 👍 

(FYI: You can add the `automerge` label to this PR to make it merge automatically when the CI passes rather than waiting)

**Comment by mrakitin** [comment]
Cool! Done :)

**Pull request merged**
